package presentacion;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.*;

/**
 * @brief Interfaz grafica para el sistema Limitless
 * @author Jeferson Castano Ossa <jcastanoossa@unicauca.edu.co>
 * @author David Santiago Giron Munoz <davidgiron@unicauca.edu.co>
*/
public class Limitless extends javax.swing.JFrame {
    
    int numFamiliares; //Numero de familiares en el plan
    int familiarActual = 1;
    
    iPaquete paqueteActual;
    //Lista de paquetes con los paquetes de cada familiar
    ArrayList<iPaquete> paquetes = new ArrayList <>();
    
    int precioTotal = 0;
    int duracionFinal = 0;

    
    public Limitless() {
        initComponents();
        initialState();
        reiniciarComponentes();
    }
    
    /**
    * @brief Inicializa componentes de vista en estados por defecto
    */
    private void initialState(){
        numFamiliares = 0;
        leerNumFamiliares(); 
        fillCbxTiposPaquetes();
        txtAreaDetallesPlan.setEditable(false);
        setLocationRelativeTo(null);
        btnFinalizar.setVisible(false);
    }
    /**
    * @brief Reinicia componentes de vista para seleccionar el paquete de un nuevo familiar
    */
    private void reiniciarComponentes(){
        txtAreaDetallesPlan.setText("");
        lbPrecioPlan.setText("");
        lbDuracionPlan.setText("");
        paqueteActual = null;
        lbPersonaN.setText("Seleccione el tipo de paquete para la persona N: " + familiarActual);            
    }
    /**
    * @brief Inicializar el numero de familiares en el plan
    */
    private void leerNumFamiliares(){

        while(numFamiliares <= 0){
            
            try{
                numFamiliares = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero de familiares:"));
                if(numFamiliares <= 0) JOptionPane.showMessageDialog(null, "Valor invalido. Ingrese numero mayores a 0.");
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null, "Ingrese solo valores numericos.");
            }
        }  
    }
    /**
    * @brief Calcula el precio total y la duracion final del paquete
    */
    private void calcularCotizacion(){
        for(iPaquete paquete: paquetes){
            precioTotal += paquete.getPrecio();
            //La duracion total es la duracion mas larga de los paquetes de cada familiar
            if (paquete.getDuracion() > duracionFinal) duracionFinal = paquete.getDuracion();
        }       
    }
    /**
    * @brief Llena el comboBox con los paquetes disponibles
    */
    private void fillCbxTiposPaquetes (){
        cbxTiposPaquetes.removeAllItems();
        cbxTiposPaquetes.addItem("<Seleccione>");
        cbxTiposPaquetes.addItem("Paquete Base");
        cbxTiposPaquetes.addItem("Paquete Pear Harbor");
        cbxTiposPaquetes.addItem("Paquete Nature");
        cbxTiposPaquetes.addItem("Paquete Amazing Hawaii");
    }
    /**
    * @brief Verificar que una accion disponible este seleccionada
    */
    private boolean isCbxTiposPaquetesSelected(){
        if(cbxTiposPaquetes.getSelectedIndex() < 1){
            JOptionPane.showMessageDialog(null, "Selecciona un paquete", "Atención", JOptionPane.INFORMATION_MESSAGE);
            txtAreaDetallesPlan.setText("");
            lbPrecioPlan.setText("");
            lbDuracionPlan.setText("");
            return false;
        }
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        lbPersonaN = new javax.swing.JLabel();
        cbxTiposPaquetes = new javax.swing.JComboBox<>();
        btnSeleccionar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDetallesPlan = new javax.swing.JTextArea();
        lbDetallesPlan = new javax.swing.JLabel();
        lbPrecio = new javax.swing.JLabel();
        lbPrecioPlan = new javax.swing.JLabel();
        lbDuracion = new javax.swing.JLabel();
        lbDuracionPlan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitulo.setText("Bienvenido a Limitless");

        lbPersonaN.setText("Seleccione el tipo de paquete para la persona N: ");

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        txtAreaDetallesPlan.setColumns(20);
        txtAreaDetallesPlan.setRows(5);
        jScrollPane1.setViewportView(txtAreaDetallesPlan);

        lbDetallesPlan.setText("Detalles Plan:");

        lbPrecio.setText("Precio: $ ");

        lbDuracion.setText("Duracion (dias): ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitulo)
                    .addComponent(btnConfirmar)
                    .addComponent(btnFinalizar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPersonaN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSeleccionar)
                            .addComponent(cbxTiposPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDetallesPlan)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbPrecio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbPrecioPlan))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbDuracion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbDuracionPlan)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbTitulo)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPersonaN)
                    .addComponent(cbxTiposPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSeleccionar)
                .addGap(18, 18, 18)
                .addComponent(btnConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinalizar)
                .addGap(121, 121, 121))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(lbDetallesPlan)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrecio)
                    .addComponent(lbPrecioPlan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDuracion)
                    .addComponent(lbDuracionPlan))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        
        if(!isCbxTiposPaquetesSelected()) return;
        String tipoPaquete = (String) cbxTiposPaquetes.getSelectedItem();
        
        //Instancia el paquete actual para el familiar
        paqueteActual = Factory.getInstance().getPaquete(tipoPaquete);
        
        txtAreaDetallesPlan.setText(paqueteActual.obtenerPlan());
        lbPrecioPlan.setText(String.valueOf(paqueteActual.getPrecio()));
        lbDuracionPlan.setText(String.valueOf(paqueteActual.getDuracion()));    
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        
        if(paqueteActual == null) {
            JOptionPane.showMessageDialog(null, "Selecciona un paquete", "Atención", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        //Agrega paquete a la lista de paquetes de los familiares
        paquetes.add(paqueteActual);
        
        //Se han ingresado todos los paquetes de los familiares
        if(numFamiliares == familiarActual){
            lbPersonaN.setVisible(false);
            btnConfirmar.setVisible(false);
            cbxTiposPaquetes.setVisible(false);
            btnSeleccionar.setVisible(false);
            
            btnFinalizar.setVisible(true);
            familiarActual--;
        }
        familiarActual++;
        reiniciarComponentes();
        JOptionPane.showMessageDialog(null, "Paquete agregado", "Atención", JOptionPane.INFORMATION_MESSAGE);     
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        
        calcularCotizacion();
        
        //Mostrar imformacion final del paquete para la familia
        for(int i = 0; i < numFamiliares; i++){
            txtAreaDetallesPlan.append("Paquete seleccionado por la persona N."+(i+1)+":\n");
            txtAreaDetallesPlan.append(paquetes.get(i).obtenerPlan());
            txtAreaDetallesPlan.append("------------------------------------------\n");
        }
        lbPrecio.setText("Precio total: $");
        lbDuracion.setText("Duracion final (dias):"); 
        
        lbPrecioPlan.setText(String.valueOf(precioTotal));
        lbDuracionPlan.setText(String.valueOf(duracionFinal)); 
    }//GEN-LAST:event_btnFinalizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JComboBox<String> cbxTiposPaquetes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDetallesPlan;
    private javax.swing.JLabel lbDuracion;
    private javax.swing.JLabel lbDuracionPlan;
    private javax.swing.JLabel lbPersonaN;
    private javax.swing.JLabel lbPrecio;
    private javax.swing.JLabel lbPrecioPlan;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextArea txtAreaDetallesPlan;
    // End of variables declaration//GEN-END:variables
}
